### ISSUE TITLE
Question about the field `group` and `excess`

### ISSUE THREAD

**Issue by Rhilip** [divijbindlish/parse-torrent-name#15]
Version : 1.1.1
```
In [6]: PTN.__version__
Out[6]: '1.1.1'
```

Hey,
Although you mentioned in the documentation that "PTN does not gaurantee the fields group, excess and episodeName as these fields might be interchanged with each other.".But I still feel that some problems exist when I use.

For example,

- In examples you give in README.md, I think that "[ettv]" should not be included in field `group`.For "ettv" is just a BT site, and add their tag at the end of torrent's name.
```
In [2]: PTN.parse('Mr Robot S01E05 HDTV x264-KILLERS[ettv]')
Out[2]:
{'codec': 'x264',
 'episode': 5,
 'group': 'KILLERS[ettv]',
 'quality': 'HDTV',
 'season': 1,
 'title': 'Mr Robot'}
```

- Or Another example,Though it Correcttly extract out the container field,but mistake the group field with container again.

```
In [5]: PTN.parse("Veep.S06E05.720p.HDTV.x264-AVS.mkv")
Out[5]:
{'codec': 'x264',
 'container': 'mkv',
 'episode': 5,
 'group': 'AVS.mkv',
 'quality': 'HDTV',
 'resolution': '720p',
 'season': 6,
 'title': 'Veep'}
```

---------------

- This torrent's name is a file pack.The season is not matched out, and It seems that season field appears into field `excess`.For your regex pattern `('season', '(s?([0-9]{1,2}))[ex]')` ,it asked a e (or x, as the begining of episode)
```
In [4]: PTN.parse("The.Flash.2014.S03.720p.HDTV.x264-Scene")
Out[4]:
{'codec': 'x264',
 'excess': 'S03',
 'group': 'Scene',
 'quality': 'HDTV',
 'resolution': '720p',
 'title': 'The Flash',
 'year': 2014}
```

Also, Some TV episodes (mainly Asian episodes), their episode tag may start as `ep`,( For example `Boku.Unmei.no.Hito.desu.Ep07.Chi_Jap.HDTVrip.1280X720-ZhuixinFan.mp4`),I hope it can be support by your package.

Thank you for your time

**Comment by roidayan** [comment]
I added pull request #18 and it seems "The.Flash.2014.S03.720p.HDTV.x264-Scene" extract season ok.

**Comment by roidayan** [comment]
As for removing BT sites from group names like KILLERS[ettv] it could be hard because you don't know if the brackets should be there or not. I guess it is possible though to make a list of known tags like ettz eztv etc and remove those.

**Comment by roidayan** [comment]
same for MKV. it is a guess because "mkv" string found but stripping from group name is difficult if "mkv" is part of the name. can guess that a ".mkv$" can be treated as file extension and stripped.

**Comment by Rhilip** [comment]
Thanks a lot for your work~

**Comment by roidayan** [comment]
no problem. though i'm not the maintainer. just added pull request and need to wait for the maintainer to approve.
