### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fastesol** [divijbindlish/parse-torrent-name#16]
is it compatible with python 3.5 or above?

**Comment by Rhilip** [comment]
Yes.It only use the official package "re".
And No problem in python 3.6.1 at my side.

**Comment by fastesol** [comment]
I'm using 3.5.2 and at my end, it gives `ImportError`

**Comment by roidayan** [comment]
if the ticket is for a question then yes it works fine with python 3.
if the ticket is for an issue then you should describe your issue and show the error.

**Comment by fastesol** [comment]
actually its not working for Python 3.5 as it says 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'PTN'
```

**Comment by roidayan** [comment]
PTN is this module
Did you install it? Or you can add the local path to sys.path.

**Comment by fastesol** [comment]
My bad, I had multiple deployments of Python 3.5 that were somehow conflicting with each other that was the actual problem. really sorry for your time and opening the ticket. 

kind regards
Muaaz
